#!/usr/bin/env python3
"""
main.py -- single entry point for the FDGL pipeline
family. Picks (dataset, drift mechanism) and dispatches, as a subprocess,
to the ALREADY-EXISTING run_*.py / embed_*.py script that implements that
combination -- this is a THIN wrapper: none of the underlying scripts'
own logic (D_asym construction, fdgl_low_dim call, plotting,
snapshotting, ...) moves here. main.py only decides which script to run
and forwards every other argument to it unchanged. The individual scripts
keep working exactly as before, standalone, if you'd rather call them
directly.

drift mechanism
----------------
    generated  = randers_bridge family (run_swiss_roll_generated.py, run_mammoth_generated.py,
                 run_sphere_radial_generated.py, run_sphere_tangential_generated.py). An
                 explicit Randers vector field omega is hand-crafted for
                 the dataset and injected into the distance matrix
                 (randers_bridge.compute_dist_matrix) -- the asymmetry is
                 GENERATED by us, ground truth is known.
    calculated = derived-omega family (run_swiss_roll_calculated.py,
                 run_mammoth_calculated.py, run_sphere_calculated.py, and the
                 MNIST/BreastCancer/scRNA embed_*.py scripts). No field is
                 hand-crafted; instead omega is DERIVED from D_asym's own
                 asymmetry (randers_bridge.compute_highdim_drift, fed
                 randers_bridge.compute_dist_matrix's plain directed k-NN
                 geodesic), then (X, omega) goes through the exact same
                 fdgl_pipeline the generated family uses -- so its asymmetry
                 is purely CALCULATED from the raw point cloud's own local
                 geometry, no privileged ground truth. [OURS 2026-09-17]
                 isumap is no longer involved anywhere in this family --
                 isumap_bridge.py and the vendored isumap/ library have both
                 been removed. Real-world datasets (MNIST, BreastCancer,
                 scRNA) only exist on this side -- there is no hand-craftable
                 "ground truth" vector field for a digit image or a cell's
                 gene expression, so they have no "generated" counterpart.

sphere is a special case: it has TWO generated variants (radial and
tangential fields, run_sphere_radial_generated.py / run_sphere_tangential_generated.py) but
only ONE calculated script (run_sphere_calculated.py), which injects no field
at all (make_sphere_points() has no omega parameter) -- so --field only
applies when --drift generated is chosen; it's ignored for calculated.

[OURS 2026-09-17] The legacy MNIST/embed_MNIST.py + MNIST/asymm_dist_MNIST.py
precompute step (never routed through this dispatcher, superseded by
embed_MNIST_raw.py/embed_MNIST_pca.py) have both been removed.

Usage
-----
    python main.py                                    # fully interactive
    python main.py --dataset swiss_roll --drift generated
    python main.py --dataset swiss_roll --drift generated --proj-dim 3
    python main.py --dataset sphere --drift generated --field radial --n 2000 --epochs 300
    python main.py --dataset mnist_raw --drift calculated --epochs 500 --force-model umap
    python main.py --list                             # show the dataset/drift/script table

Anything after --dataset/--drift/--field/--proj-dim is forwarded AS-IS to
the underlying script (its own --n, --epochs, --k, --force-model, --ramp,
--gravity, --adjacency, ... all still work exactly as documented in that
script's own --help).

[OURS 2026-09-15] --proj-dim (2D vs 3D output) was already implemented in
the 7 underlying swiss_roll/mammoth/sphere scripts (both drift families),
and technically already reached them via forward_args even before this
flag existed here -- but it was invisible in `main.py --help` and silently
accepted (then crashed inside the child script) for datasets that don't
support it (mnist/breast_cancer/scrna are fixed 2D). Declaring it
explicitly here makes it discoverable and lets us validate it up front
with a clear error instead of a confusing traceback from the child script.
"""

import argparse
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# ─────────────────────────────────────────────────────────────────────────────
# dataset -> {"generated": <script or None>, "calculated": <script or None>}
# paths are relative to HERE (this file's own directory).
# ─────────────────────────────────────────────────────────────────────────────
DATASETS = {
    "swiss_roll": {
        "generated": "run_swiss_roll_generated.py",
        "calculated": "run_swiss_roll_calculated.py",
    },
    "mammoth": {
        "generated": "run_mammoth_generated.py",
        "calculated": "run_mammoth_calculated.py",
    },
    "sphere": {
        # "generated" needs --field too (see SPHERE_FIELD_SCRIPTS below);
        # left as None here since it's not a single fixed script.
        "generated": None,
        "calculated": "run_sphere_calculated.py",
    },
    "mnist_raw": {
        "generated": None,
        "calculated": "MNIST/embed_MNIST_raw.py",
    },
    "mnist_pca": {
        "generated": None,
        "calculated": "MNIST/embed_MNIST_pca.py",
    },
    "breast_cancer": {
        "generated": None,
        "calculated": "BreastCancer/embed_BreastCancer.py",
    },
    "scrna": {
        "generated": None,
        "calculated": "scRNA/embed_scRNA.py",
    },
}

SPHERE_FIELD_SCRIPTS = {
    "radial": "run_sphere_radial_generated.py",
    "tangential": "run_sphere_tangential_generated.py",
}

# [OURS 2026-09-15] datasets whose underlying script(s) accept --proj-dim
# {2,3} (added 2026-08-20/21, see script docstrings). mnist_raw/mnist_pca/
# breast_cancer/scrna's embed_*.py scripts have no such flag -- they're
# fixed 2D -- so --proj-dim is rejected up front for those instead of
# being silently forwarded and crashing inside the child script.
PROJ_DIM_SUPPORTED = {"swiss_roll", "mammoth", "sphere"}

DATASET_LABELS = {
    "swiss_roll": "Swiss roll",
    "mammoth": "Mammoth",
    "sphere": "Sphere",
    "mnist_raw": "MNIST (raw 784D)",
    "mnist_pca": "MNIST (PCA-reduced)",
    "breast_cancer": "Breast Cancer",
    "scrna": "scRNA",
}


def _available_drifts(dataset: str) -> list:
    return [d for d in ("generated", "calculated") if DATASETS[dataset][d] is not None
            or (dataset == "sphere" and d == "generated")]


def _prompt_choice(prompt: str, options: list, labels: dict = None) -> str:
    labels = labels or {}
    print(prompt)
    for i, opt in enumerate(options, 1):
        print(f"  {i}. {labels.get(opt, opt)}")
    while True:
        raw = input(f"Seçim [1-{len(options)}]: ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw) - 1]
        print(f"Geçersiz seçim, 1-{len(options)} arası bir sayı gir.")


def print_table():
    print(f"{'dataset':<14} {'generated':<28} {'calculated':<32}")
    print("-" * 76)
    for ds, mapping in DATASETS.items():
        gen = mapping["generated"] or ("radial/tangential (--field)" if ds == "sphere" else "-")
        calc = mapping["calculated"] or "-"
        print(f"{ds:<14} {gen:<28} {calc:<32}")


def resolve_script(dataset: str, drift: str, field: str = None) -> Path:
    if dataset == "sphere" and drift == "generated":
        if field is None:
            field = _prompt_choice("Hangi field?", ["radial", "tangential"])
        if field not in SPHERE_FIELD_SCRIPTS:
            sys.exit(f"--field must be 'radial' or 'tangential', got {field!r}")
        return HERE / SPHERE_FIELD_SCRIPTS[field]

    script = DATASETS[dataset][drift]
    if script is None:
        available = _available_drifts(dataset)
        sys.exit(f"{dataset!r} has no {drift!r} pipeline -- available: {available}")
    return HERE / script


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dataset", choices=list(DATASETS.keys()), default=None)
    p.add_argument("--drift", choices=["generated", "calculated"], default=None)
    p.add_argument("--field", choices=["radial", "tangential"], default=None,
                    help="only used for --dataset sphere --drift generated")
    p.add_argument("--proj-dim", type=int, choices=[2, 3], default=None,
                    help="2D or 3D output embedding. Only supported for "
                         "swiss_roll/mammoth/sphere (both drift mechanisms) -- "
                         "mnist_raw/mnist_pca/breast_cancer/scrna are 2D-only.")
    p.add_argument("--list", action="store_true",
                    help="print the dataset/drift -> script table and exit")
    args, forward_args = p.parse_known_args()

    if args.list:
        print_table()
        return

    dataset = args.dataset
    if dataset is None:
        dataset = _prompt_choice("Hangi dataset?", list(DATASETS.keys()), DATASET_LABELS)

    available = _available_drifts(dataset)
    drift = args.drift
    if drift is None:
        if len(available) == 1:
            drift = available[0]
            print(f"({DATASET_LABELS[dataset]} sadece 'calculated' destekliyor -- otomatik seçildi.)")
        else:
            drift = _prompt_choice("Generated mi, calculated mi?", available)
    elif drift not in available:
        sys.exit(f"{dataset!r} has no {drift!r} pipeline -- available: {available}")

    script = resolve_script(dataset, drift, args.field)
    if not script.exists():
        sys.exit(f"Beklenen script bulunamadı: {script}")

    if args.proj_dim is not None:
        if dataset not in PROJ_DIM_SUPPORTED:
            sys.exit(f"--proj-dim not supported for {dataset!r} -- "
                      f"only {sorted(PROJ_DIM_SUPPORTED)} accept it "
                      f"({DATASET_LABELS[dataset]} is 2D-only).")
        forward_args = ["--proj-dim", str(args.proj_dim)] + forward_args

    print(f"-> {script.relative_to(HERE)}  {' '.join(forward_args)}")
    result = subprocess.run([sys.executable, str(script)] + forward_args, cwd=HERE)
    sys.exit(result.returncode)


if __name__ == "__main__":
    main()
