#!/usr/bin/env python3
"""
main.py -- [OURS 2026-09-10] single entry point for the FDGL pipeline
family. Picks (dataset, drift mechanism) and dispatches, as a subprocess,
to the ALREADY-EXISTING run_*.py / embed_*.py script that implements that
combination -- this is a THIN wrapper: none of the underlying scripts'
own logic (D_asym construction, randers_umap_fit call, plotting,
snapshotting, ...) moves here. main.py only decides which script to run
and forwards every other argument to it unchanged. The individual scripts
keep working exactly as before, standalone, if you'd rather call them
directly.

drift mechanism
----------------
    generated  = randers_bridge family (run_swiss_roll.py, run_mammoth.py,
                 run_sphere_radial.py, run_sphere_tangential.py). An
                 explicit Randers vector field omega is hand-crafted for
                 the dataset and injected into the distance matrix
                 (randers_bridge.compute_dist_matrix) -- the asymmetry is
                 GENERATED by us, ground truth is known.
    calculated = isumap family (run_swiss_roll_isumap.py,
                 run_mammoth_isumap.py, run_sphere_isumap.py, and the
                 MNIST/BreastCancer/scRNA embed_*.py scripts). No field is
                 injected; D_asym comes from isumap_bridge's own directed
                 k-NN/shortest-path construction (build_isumap_dist_matrix
                 / distance_graph_generation), so its asymmetry is purely
                 CALCULATED from the raw point cloud's own local geometry,
                 no privileged ground truth. Real-world datasets (MNIST,
                 BreastCancer, scRNA) only exist on this side -- there is
                 no hand-craftable "ground truth" vector field for a digit
                 image or a cell's gene expression, so they have no
                 "generated" counterpart.

sphere is a special case: it has TWO generated variants (radial and
tangential fields, run_sphere_radial.py / run_sphere_tangential.py) but
only ONE calculated script (run_sphere_isumap.py), which injects no field
at all (make_sphere_points() has no omega parameter) -- so --field only
applies when --drift generated is chosen; it's ignored for calculated.

Explicitly OUT OF SCOPE (per project discussion, 2026-09-10): the legacy
MNIST/embed_MNIST.py (superseded by embed_MNIST_raw.py/embed_MNIST_pca.py,
depends on a separate asymm_dist_MNIST.py precompute step) and
run_swiss_roll_generated.py (a third swiss_roll+generated sub-variant,
differing only in which omega field formula is used) -- both remain
available as their own standalone scripts, just not routed through here.

Usage
-----
    python main.py                                    # fully interactive
    python main.py --dataset swiss_roll --drift generated
    python main.py --dataset sphere --drift generated --field radial --n 2000 --epochs 300
    python main.py --dataset mnist_raw --drift calculated --epochs 500 --force-model umap
    python main.py --list                             # show the dataset/drift/script table

Anything after --dataset/--drift/--field is forwarded AS-IS to the
underlying script (its own --n, --epochs, --k, --force-model, --ramp,
--gravity, --adjacency, ... all still work exactly as documented in that
script's own --help).
"""

import argparse
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# ─────────────────────────────────────────────────────────────────────────────
# dataset -> {"generated": <script or None>, "calculated": <script or None>}
# paths are relative to HERE (this file's own directory).
# ─────────────────────────────────────────────────────────────────────────────
DATASETS = {
    "swiss_roll": {
        "generated": "run_swiss_roll.py",
        "calculated": "run_swiss_roll_isumap.py",
    },
    "mammoth": {
        "generated": "run_mammoth.py",
        "calculated": "run_mammoth_isumap.py",
    },
    "sphere": {
        # "generated" needs --field too (see SPHERE_FIELD_SCRIPTS below);
        # left as None here since it's not a single fixed script.
        "generated": None,
        "calculated": "run_sphere_isumap.py",
    },
    "mnist_raw": {
        "generated": None,
        "calculated": "MNIST/embed_MNIST_raw.py",
    },
    "mnist_pca": {
        "generated": None,
        "calculated": "MNIST/embed_MNIST_pca.py",
    },
    "breast_cancer": {
        "generated": None,
        "calculated": "BreastCancer/embed_BreastCancer.py",
    },
    "scrna": {
        "generated": None,
        "calculated": "scRNA/embed_scRNA.py",
    },
}

SPHERE_FIELD_SCRIPTS = {
    "radial": "run_sphere_radial.py",
    "tangential": "run_sphere_tangential.py",
}

DATASET_LABELS = {
    "swiss_roll": "Swiss roll",
    "mammoth": "Mammoth",
    "sphere": "Sphere",
    "mnist_raw": "MNIST (raw 784D)",
    "mnist_pca": "MNIST (PCA-reduced)",
    "breast_cancer": "Breast Cancer",
    "scrna": "scRNA",
}


def _available_drifts(dataset: str) -> list:
    return [d for d in ("generated", "calculated") if DATASETS[dataset][d] is not None
            or (dataset == "sphere" and d == "generated")]


def _prompt_choice(prompt: str, options: list, labels: dict = None) -> str:
    labels = labels or {}
    print(prompt)
    for i, opt in enumerate(options, 1):
        print(f"  {i}. {labels.get(opt, opt)}")
    while True:
        raw = input(f"Seçim [1-{len(options)}]: ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw) - 1]
        print(f"Geçersiz seçim, 1-{len(options)} arası bir sayı gir.")


def print_table():
    print(f"{'dataset':<14} {'generated':<28} {'calculated':<32}")
    print("-" * 76)
    for ds, mapping in DATASETS.items():
        gen = mapping["generated"] or ("radial/tangential (--field)" if ds == "sphere" else "-")
        calc = mapping["calculated"] or "-"
        print(f"{ds:<14} {gen:<28} {calc:<32}")


def resolve_script(dataset: str, drift: str, field: str = None) -> Path:
    if dataset == "sphere" and drift == "generated":
        if field is None:
            field = _prompt_choice("Hangi field?", ["radial", "tangential"])
        if field not in SPHERE_FIELD_SCRIPTS:
            sys.exit(f"--field must be 'radial' or 'tangential', got {field!r}")
        return HERE / SPHERE_FIELD_SCRIPTS[field]

    script = DATASETS[dataset][drift]
    if script is None:
        available = _available_drifts(dataset)
        sys.exit(f"{dataset!r} has no {drift!r} pipeline -- available: {available}")
    return HERE / script


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dataset", choices=list(DATASETS.keys()), default=None)
    p.add_argument("--drift", choices=["generated", "calculated"], default=None)
    p.add_argument("--field", choices=["radial", "tangential"], default=None,
                    help="only used for --dataset sphere --drift generated")
    p.add_argument("--list", action="store_true",
                    help="print the dataset/drift -> script table and exit")
    args, forward_args = p.parse_known_args()

    if args.list:
        print_table()
        return

    dataset = args.dataset
    if dataset is None:
        dataset = _prompt_choice("Hangi dataset?", list(DATASETS.keys()), DATASET_LABELS)

    available = _available_drifts(dataset)
    drift = args.drift
    if drift is None:
        if len(available) == 1:
            drift = available[0]
            print(f"({DATASET_LABELS[dataset]} sadece 'calculated' destekliyor -- otomatik seçildi.)")
        else:
            drift = _prompt_choice("Generated mi, calculated mi?", available)
    elif drift not in available:
        sys.exit(f"{dataset!r} has no {drift!r} pipeline -- available: {available}")

    script = resolve_script(dataset, drift, args.field)
    if not script.exists():
        sys.exit(f"Beklenen script bulunamadı: {script}")

    print(f"-> {script.relative_to(HERE)}  {' '.join(forward_args)}")
    result = subprocess.run([sys.executable, str(script)] + forward_args, cwd=HERE)
    sys.exit(result.returncode)


if __name__ == "__main__":
    main()
